-- MySQL Script generated by MySQL Workbench
-- ven. 24 juin 2022 08:38:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Jarvis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Jarvis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jarvis` DEFAULT CHARACTER SET utf8 ;
USE `Jarvis` ;

-- -----------------------------------------------------
-- Table `Jarvis`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Utilisateur` (
  `id_u` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prenom_u` VARCHAR(100) NOT NULL,
  `nom_u` VARCHAR(100) NOT NULL,
  `date_de_naissance` DATE NOT NULL,
  `email_u` VARCHAR(50) NOT NULL,
  `sexe` VARCHAR(1) NULL,
  `mdp_u` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_u`),
  UNIQUE INDEX `id_u_UNIQUE` (`id_u` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Membre` (
  `id_m` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lien_parente` INT NOT NULL DEFAULT 0,
  `id_u_membre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_m`, `id_u_membre`),
  UNIQUE INDEX `id_m_UNIQUE` (`id_m` ASC) VISIBLE,
  INDEX `fk_Membre_Utilisateur_idx` (`id_u_membre` ASC) VISIBLE,
  UNIQUE INDEX `id_u_membre_UNIQUE` (`id_u_membre` ASC) VISIBLE,
  CONSTRAINT `fk_Membre_Utilisateur`
    FOREIGN KEY (`id_u_membre`)
    REFERENCES `Jarvis`.`Utilisateur` (`id_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`CoProprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`CoProprietaire` (
  `id_copro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_u_copro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_copro`, `id_u_copro`),
  UNIQUE INDEX `id_copro_UNIQUE` (`id_copro` ASC) VISIBLE,
  INDEX `fk_CoProprietaire_Utilisateur_idx` (`id_u_copro` ASC) VISIBLE,
  UNIQUE INDEX `id_u_copro_UNIQUE` (`id_u_copro` ASC) VISIBLE,
  CONSTRAINT `fk_CoProprietaire_Utilisateur`
    FOREIGN KEY (`id_u_copro`)
    REFERENCES `Jarvis`.`Utilisateur` (`id_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Proprietaire` (
  `id_pro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_u_pro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pro`, `id_u_pro`),
  UNIQUE INDEX `id_pro_UNIQUE` (`id_pro` ASC) VISIBLE,
  INDEX `fk_Proprietaire_Utilisateur_idx` (`id_u_pro` ASC) VISIBLE,
  UNIQUE INDEX `id_u_pro_UNIQUE` (`id_u_pro` ASC) VISIBLE,
  CONSTRAINT `fk_Proprietaire_Utilisateur`
    FOREIGN KEY (`id_u_pro`)
    REFERENCES `Jarvis`.`Utilisateur` (`id_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Domicile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Domicile` (
  `id_domicile` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `anne_de_construction` YEAR NOT NULL DEFAULT 2000,
  `superficie` DOUBLE NULL DEFAULT 0,
  `id_pro_domicile` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_domicile`, `id_pro_domicile`),
  UNIQUE INDEX `id_domicile_UNIQUE` (`id_domicile` ASC) VISIBLE,
  INDEX `fk_Domicile_Proprietaire1_idx` (`id_pro_domicile` ASC) VISIBLE,
  CONSTRAINT `fk_Domicile_Proprietaire`
    FOREIGN KEY (`id_pro_domicile`)
    REFERENCES `Jarvis`.`Proprietaire` (`id_pro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Pieces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Pieces` (
  `id_piece` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_piece` VARCHAR(45) NOT NULL,
  `id_domicile_piece` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_piece`, `id_domicile_piece`),
  UNIQUE INDEX `id_piece_UNIQUE` (`id_piece` ASC) VISIBLE,
  INDEX `fk_Pieces_Domicile1_idx` (`id_domicile_piece` ASC) VISIBLE,
  CONSTRAINT `fk_Pieces_Domicile1`
    FOREIGN KEY (`id_domicile_piece`)
    REFERENCES `Jarvis`.`Domicile` (`id_domicile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Appareils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Appareils` (
  `id_appareil` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_appareil` VARCHAR(45) NOT NULL,
  `type_appareil` VARCHAR(45) NOT NULL,
  `id_piece_appareil` INT UNSIGNED NOT NULL,
  `id_domicile_piece_appareil` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_appareil`, `id_piece_appareil`, `id_domicile_piece_appareil`),
  UNIQUE INDEX `id_appareil_UNIQUE` (`id_appareil` ASC) VISIBLE,
  INDEX `fk_Appareils_Pieces1_idx` (`id_piece_appareil` ASC, `id_domicile_piece_appareil` ASC) VISIBLE,
  CONSTRAINT `fk_Appareils_Pieces`
    FOREIGN KEY (`id_piece_appareil` , `id_domicile_piece_appareil`)
    REFERENCES `Jarvis`.`Pieces` (`id_piece` , `id_domicile_piece`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Habiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Habiter` (
  `id_domicile` INT UNSIGNED NOT NULL,
  `id_u` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_domicile`, `id_u`),
  INDEX `fk_Utilisateur_Domicile_Habiter_idx` (`id_u` ASC) VISIBLE,
  INDEX `fk_Domicile_Utilisateur_Habiter_idx` (`id_domicile` ASC) VISIBLE,
  CONSTRAINT `fk_Domicile_Utilisateur_Habiter`
    FOREIGN KEY (`id_domicile`)
    REFERENCES `Jarvis`.`Domicile` (`id_domicile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Utilisateur_Domicile_Habiter`
    FOREIGN KEY (`id_u`)
    REFERENCES `Jarvis`.`Utilisateur` (`id_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Inviter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Inviter` (
  `id_u` INT UNSIGNED NOT NULL,
  `id_pro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_u`, `id_pro`),
  INDEX `fk_Proprietaire_Inviter_Utilisateur_idx` (`id_pro` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Inviter_Proprietaire_idx` (`id_u` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_Inviter_Proprietaire`
    FOREIGN KEY (`id_u`)
    REFERENCES `Jarvis`.`Utilisateur` (`id_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Proprietaire_Inviter_Utilisateur`
    FOREIGN KEY (`id_pro`)
    REFERENCES `Jarvis`.`Proprietaire` (`id_pro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
